# Generated by Django 2.2.4 on 2019-08-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_details',
        ),
    ]
